version: '2'
services:
  erddap:
    container_name: "erddap_gold_standard"
    image: axiom/docker-erddap:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - "${PWD}/erddap/conf/setenv.sh:/usr/local/tomcat/bin/setenv.sh"
      - "${PWD}/erddap/conf/robots.txt:/usr/local/tomcat/webapps/ROOT/robots.txt"
      - "${PWD}/erddap/content:/usr/local/tomcat/content/erddap"
      - "${PWD}/erddap/data:/erddapData"
      - "${PWD}/datasets:/datasets"
      - "/tmp/:/usr/local/tomcat/temp/"
